[Create the data models]
eid-sonkrot/RestaurantReservation pull request #1
Opened 2023-09-21 19:42 UTC by eid-sonkrot

in this commit i create all database table and set all keys and relations

2023-09-24 07:43 UTC, ahmad-m-abbas requested changes
Good in general, but it is better to store the id of the object instead of the object itself.

2023-09-24 07:43 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/Customer.cs
> +        public ICollection<Reservation> Reservations { get; set; }
Why not to store reservations Ids instead of the whole object. If needed, we can fetch it from the database.

Same comment for all collections.

2023-09-24 07:43 UTC, ahmad-m-abbas commented on RestaurantReservation.Db/OrderItem.cs
> +        public Order order { get; set; }
Same comment here. Store Order Id instead of the object.

2023-10-30 19:43 UTC, Alatrash814 requested changes
Please update the things that we agreed to do.

2023-10-30 19:43 UTC, Alatrash814 commented on RestaurantReservation.Db/Customer.cs
> +        public int customer_id { get; set; }
[Column("customer_id")]
        public int CustomerId { get; set; }

2023-10-30 19:43 UTC, Alatrash814 commented on RestaurantReservation.Db/Reservation.cs
> +        public int table_id { get; set;}
no need for these props.

2023-10-30 19:43 UTC, Alatrash814 commented on RestaurantReservation.Db/Reservation.cs
> +        public Order  orders { get;set;}
```suggestion
       [Column("order")]
        public Order Order {  get; set; } 
```

2023-11-14 01:02 UTC, closed without merging